### ISSUE TITLE
setupSupabase() and auth() not working

### ISSUE THREAD

**Issue by Protract-123** [david-plugge/supabase-auth-helpers-sk-new-api#11]
When using setupSupabase() on my +layout.svelte file, when I pass in my supabase client I get an error when I open my page
Error: You need to pass the your supabase instance to `setClientConfig`. This same bug also occurs in my hooks.server.ts file in the auth() function

**To Reproduce**

I used all the code which was provided in the auth part of the repository and this occurred.
note: I named my supabase client "supabase" instead of "supabaseClient"

Screenshots:
<img width="1188" alt="Screenshot 2022-09-25 at 12 14 39 AM" src="https://user-images.githubusercontent.com/70811078/192113835-c5654db8-978e-4606-8613-d96d7f86726a.png">

<img width="587" alt="Screenshot 2022-09-25 at 12 15 06 AM" src="https://user-images.githubusercontent.com/70811078/192113849-6fde2afa-f2a9-4f78-b2f1-3b2a855d9b8c.png">

<img width="460" alt="Screenshot 2022-09-25 at 12 17 44 AM" src="https://user-images.githubusercontent.com/70811078/192113954-5dc35fa1-17d1-4e31-923f-d07f2c3d5803.png">

**Comment by david-plugge** [comment]
`setupSupabase` and `auth` expect an object as the first parameter with a key `supabaseClient`.
If you want something else than that you can pass it like this:

```ts
setupSupabase({
	supabaseClient: supabase,
	...
})
```

However, the auth package is likely going to be removed once the [supabase auth helpers](https://github.com/supabase/auth-helpers/tree/main/packages/sveltekit) are updated to work with the new sveltekit routing.
I will add that in the readme.
