### ISSUE TITLE
feat: styling

### ISSUE THREAD

**Issue by ryanrussell** [david-plugge/supabase-auth-helpers-sk-new-api#2]
### Feature Description: Styling
- Add some basic styling to the demo
- Suggest tailwind. (**opinionated**)?
- modularizing design templates feels higher level of effort to / lower value than merchants
- perhaps choose single lib (tailwind **or** something else)?  

#### Questions
- Is skinning this in scope for your intent?
- Do you have something you prefer to tailwind?
- Am I missing an easy way to modularize this?

Again, happy to help...

Thoughts?

**Comment by david-plugge** [comment]
This is mainly a brainstorming repo just used for testing until we get a new release of supabase auth helpers so i dont think we need styling.
But in case you want to style this just create a PR :) And i´m happy with tailwind

**Comment by ryanrussell** [comment]
Got it.

If the intent of this repo is to be temporary and discarded when the new release comes, it doesn't make any sense to put cycles into styling.
