### ISSUE TITLE
import PageLoad Module '"./$types"' has no exported member 'PageLoad'

### ISSUE THREAD

**Issue by jrfii-animation** [david-plugge/supabase-auth-helpers-sk-new-api#3]
Hello, David!

First, I'd like to say a huge thank you for the wonderful work that you've put in over this past week. It's been a painful week for me, and I'd still be completely lost without your assistance.

I keep getting the above error whenever I restructure your code to fit my needs. This is the first time I'm using TypeScript, so my attempts at sorting out this error continue to fail. Any suggestions for what I could do to fix this problem?

Also, when I call the LayoutServerLoad function, I'm getting errors on both "user" and "accessToken":

Property 'user' does not exist on type 'Locals'

Property 'accessToken' does not exist on type 'Locals'

 Any suggestions for how I could correct this error as well?

Thank you for your time and assistance. And, again, I greatly appreciate your efforts!

Best,

John

**Comment by david-plugge** [comment]
Hi John, i´m happy to help :)

How did you setup your project? Did you try to manually copy the code into your existing project? Or cloned this repo?
SvelteKit generates types for every route, but only if typescript is installed.

> Property 'user' does not exist on type 'Locals' 
> Property 'accessToken' does not exist on type 'Locals'

Have you set up _src/app.d.ts_?

> Also, when I call the LayoutServerLoad function

What do you mean by _calling_ the function? you should not call it yourself, it will be executed by sveltekit

**Comment by jrfii-animation** [comment]
Hello, David!

Thank you for your prompt response.

I've cloned your repo, manually edited a previously cloned file to include your subsequent updates and rebuilt my project on multiple occasions. When I directly clone your project, everything works just fine. When I manually entered your subsequent updates into a previously cloned file, I received errors. These same errors are present in my rebuilds.

Please ignore my previous comment regarding "calling" the function. That's not what I meant. Actually, the code works as intended, but, despite the Session being properly defined, the errors persist.

In order to better explain where I'm receiving errors, I created a repo to share with you:

https://github.com/jrfii-animation/testingSveltekitSupabase

You'll see that I'm getting errors in 4 files, including:

/contributor-portal/layout

/contributor-portal/create-profile/page.server.ts

/package/helpers.ts (which includes your most recent updates)

/package/server/handlers/session.ts

I believe that all of these errors are due to the two previously mentioned issues, but there appears to be a third with "SupabaseSession" not being recognized.

My test file is also acting a little funky at the moment; I'm not seeking assistance with these issues (though I'm open to suggestions). In this shared test file, you'll have to refresh the page after a sign-up; seems to be an issue with my redirects. Also, my create-profile upsert is failing at the moment. I'll continue to try to address these errors, but I just wanted to share this file with you before I ran out to take care of some other business, in the hope that I'll be able to get back to finalizing my original code base as soon as possible.

Thank you for your time and assistance. 

Best,

John

**Comment by david-plugge** [comment]
Thanks for creating a repro, thats very convenient.

_/contributor-portal/create-profile/page.server.ts_
This is a `.server` file so the export should be a `PageServerLoad`
```ts
import { serverLoadWithSession } from '../../../../package';
import type { PageServerLoad } from './$types';

export const load: PageServerLoad = serverLoadWithSession({ status: 303, location: '/contributor-portal/dashboard' }, async ({ session }) => {
    return session;
});
```
You don´t have to check if the session exists, the helper does it internally. The config object is used to tell sveltekit where to redirect the user if there is no session.

All the other errors are caused by the import in _app.d.ts_. You can´t import or export in an ambient file or it will be treated as a module. So all the types just disappeared. 

And in case you didn´t know, you can easily get rid of the `../../` hell:
```ts
// svelte.config.js
const config = {
	kit: {
		alias: {
			"$supabase-helpers": "src/package"
		}
	}
};
```

**Comment by jrfii-animation** [comment]
Goodness gracious! All of those errors regarding "property does not exist" were due to me forgetting to comment out a line of code--what a ditz! ;p I was trying to add a "Profile" object to my user but am still pretty lost when it comes to TypeScript. My quick fix was to just inject the Profile into the User's metadata object; any thoughts on this?

What determines whether a file should be a page.server.ts or page.ts? I have other routes that exist for users that have already created a Profile, should these pages be page.server.ts files where I just pass along the session as you've done above? I see that you used a post.ts file in your example, should I do the same on the create-profile page, as well as any page where a user creates, edits or deletes? Sorry for all my questions, all of these changes have me so confused. :)

In my working file, I have placed the "package" folder in the "lib" folder to prevent dot-dot hell, would you consider doing so a bad practice?

I'll make my test repository private very soon, as I wouldn't want to pass off your hard work as my own.

Thank you so much for everything, David!

**Comment by david-plugge** [comment]
So in general you always _want_ to you use `+page` files and only fall back to `+page.server` files when you access resources that are only accessible on the server like a private env variable. That way your client gets the data directly from the api.
With supabase you can almost always use `+page` files.

Supabase uses postgres so i´d suggest going the sql way and creating a separate table for profiles. They also have a [guide](https://supabase.com/docs/guides/auth/managing-user-data) about that topic

You´re welcome :)
