### ISSUE TITLE
chore: canonicalize `auth-helpers` package namespace

### ISSUE THREAD

**Issue by ryanrussell** [david-plugge/supabase-auth-helpers-sk-new-api#8]
# Issue
Multiple names for `supabase-auth-helpers-sveltekit`

### Variances in naming

1. It's just called `auth-helpers` in the main readme.
  - README.md: `[auth-helpers](packages/supabase-auth-helpers-sveltekit/)`

2. `@supabase` vs `supabase-`
  ```bash
  grep -r '@supabase/auth-helpers-sveltekit' | wc -l
  9
  r@rockin:~/lab/sveltekit-supabase$ grep -r 'supabase-auth-helpers-sveltekit' | wc -l
  86
  ```

3. package.json 
  `supabase-auth-helpers` vs `supabase-auth-helpers-sveltekit`
  ```
          "dev:supabase-auth-helpers": "turbo run dev --filter supabase-auth-helpers-sveltekit",
          "build:supabase-auth-helpers": "turbo run build --filter supabase-auth-helpers-sveltekit",
  ```

Which should it be? Let's pick one and update everywhere.

**Comment by david-plugge** [comment]
Should be resolved now. It´s called `sveltekit-supabase-auth` now to follow the `sveltekit-supabase-[package]` convention
